## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Process media by using serverless job management and ephemeral compute workers"
stackDescription: "Process media by using serverless job management and ephemeral compute workers."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - create_job_function_version
  - launch_worker_function_version
  - check_preempted_worker_function_version
  - retry_queued_function_version

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - email_address
  - ocir_user_name
  - ocir_password
  - show_advanced 

- title: Network Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - vcn_cidr
  - public_subnet_cidr
  - private_subnet_cidr

- title: OSS Bucket Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - source_bucket_name
  - destination_bucket_name

- title: OCIR Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:      
  - ocir_repo_name

variables:
  
  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: "Compartment"
    description: "Choose compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: "Region"
    description: "Choose region where you want to deploy the resources defined by this stack."

  ocir_user_name:
    type: string
    required: true
    visibile: true
    title: "OCIR username"
    description: "Oracle Cloud Infrastructure Registry username (your OCI username)" 

  ocir_password:
    type: password
    required: true
    visibile: true
    title: "OCIR user password"
    description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)" 

  # Optional Configuration
  vcn_cidr:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN's CIDR block where Fn App will be deployed."

  public_subnet_cidr:
    type: string
    required: false
    default: "10.0.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Public Subnet CIDR"
    description: "Choose Public Subnet's CIDR."  

  private_subnet_cidr:
    type: string
    required: false
    default: "10.0.0.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Private Subnet CIDR"
    description: "Choose Private Subnet's CIDR."  

  source_bucket_name:
    type: string
    required: false
    default: "transcode_source"
    title: "Source Bucket Name"
    description: "Choose source bucket name"

  destination_bucket_name:
    type: string
    required: false
    default: "transcode_destination"
    title: "Destination Bucket Name"
    description: "Choose destination bucket name"

  ocir_repo_name:
    type: string
    required: false
    default: "job_management"
    title: "OCIR repo name"
    description: "Oracle Cloud Infrastructure Registry repository name"

